# Generated by Django 4.1.7 on 2023-04-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_email_user_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='costs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.costs'),
        ),
    ]
