# Generated by Django 4.1.7 on 2023-03-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_username_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
