# Generated by Django 4.1.7 on 2023-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='userID',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
