# Generated by Django 4.1.7 on 2023-04-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='costs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='main.costs'),
        ),
        migrations.AlterField(
            model_name='data',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to=settings.AUTH_USER_MODEL),
        ),
    ]
