# Generated by Django 4.1.7 on 2023-03-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datameter',
            name='userID',
        ),
    ]
