# Generated by Django 4.1.7 on 2023-04-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_data_costs_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='userID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL),
        ),
    ]
