# Generated by Django 4.2 on 2023-04-18 19:04

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_data_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='electroSumm',
            field=models.CharField(max_length=10, validators=[main.validators.validate_electroSumm], verbose_name='Сумма за энергию'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gasSumm',
            field=models.CharField(max_length=10, validators=[main.validators.validate_gasSumm], verbose_name='Сумма за газ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='waterSumm',
            field=models.CharField(max_length=10, validators=[main.validators.validate_waterSumm], verbose_name='Сумма за воду'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, validators=[main.validators.validate_first_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, validators=[main.validators.validate_last_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='licSchet',
            field=models.CharField(max_length=11, unique=True, validators=[main.validators.validate_licSchet], verbose_name='Лицевой Счет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residents',
            field=models.IntegerField(default=3, validators=[main.validators.validate_residents], verbose_name='Кол-во жильцов'),
        ),
    ]
