# Generated by Django 4.1.7 on 2023-04-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_datameter_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataMeter',
            new_name='Data',
        ),
    ]
