# Generated by Django 4.1.7 on 2023-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_costs_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения показаний'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='electroCost',
            field=models.CharField(max_length=10, verbose_name='Потребление энергии'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='gasCost',
            field=models.CharField(max_length=10, verbose_name='Потребление газа'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='waterCost',
            field=models.CharField(max_length=10, verbose_name='Потребление воды'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения показаний'),
        ),
        migrations.AlterField(
            model_name='data',
            name='electro',
            field=models.CharField(max_length=10, verbose_name='Показания счетчика энергии'),
        ),
        migrations.AlterField(
            model_name='data',
            name='gas',
            field=models.CharField(max_length=10, verbose_name='Показания газового счетчика'),
        ),
        migrations.AlterField(
            model_name='data',
            name='water',
            field=models.CharField(max_length=10, verbose_name='Показания водяного счетчика'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания квитанции'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='electroSumm',
            field=models.CharField(max_length=10, verbose_name='Сумма за энергию'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gasSumm',
            field=models.CharField(max_length=10, verbose_name='Сумма за газ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='repairSumm',
            field=models.CharField(max_length=10, verbose_name='Сумма за обслуживание дома'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.CharField(max_length=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='trashSumm',
            field=models.CharField(max_length=10, verbose_name='Сумма за мусор'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='waterSumm',
            field=models.CharField(max_length=10, verbose_name='Сумма за воду'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='licSchet',
            field=models.CharField(max_length=11, unique=True, verbose_name='Лицевой Счет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residents',
            field=models.IntegerField(default=3, verbose_name='Кол-во жильцов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
