# Generated by Django 4.1.7 on 2023-04-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
